# Generated by Django 4.2.3 on 2023-08-14 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nickname", models.CharField(max_length=20)),
                ("country", models.CharField(max_length=10)),
                ("city", models.CharField(max_length=10)),
                (
                    "profile_img",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=profiles.models.image_upload_path,
                    ),
                ),
                (
                    "followings",
                    models.ManyToManyField(
                        related_name="followers", to="profiles.profile"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
