# Generated by Django 4.2.3 on 2023-08-14 06:43

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_img",
            field=models.ImageField(
                blank=True,
                default="default/default_profile_img.png",
                null=True,
                upload_to=profiles.models.image_upload_path,
            ),
        ),
    ]
