# Generated by Django 4.2.3 on 2023-08-15 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_followings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="followings",
        ),
    ]
