# Generated by Django 4.2.3 on 2023-08-12 16:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Discussion', '0003_alter_choice_voted_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='voted_user',
        ),
        migrations.AddField(
            model_name='choice',
            name='voted_user',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
