# Generated by Django 4.2.3 on 2023-08-11 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion', '0003_remove_comment_record_choice_discussion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 11, 20, 49, 16, 362159)),
        ),
    ]
