# Generated by Django 4.2.3 on 2023-08-12 05:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion', '0012_alter_comment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 12, 14, 50, 38, 540716)),
        ),
    ]
