# Generated by Django 4.2.3 on 2023-08-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Companion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
