# Generated by Django 4.2.3 on 2023-08-11 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Companion', '0002_companion_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companion',
            old_name='comments_cnt',
            new_name='comments_count',
        ),
    ]
