# Generated by Django 4.2.3 on 2023-08-11 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Companion', '0003_rename_comments_cnt_companion_comments_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cocomment',
            old_name='Companion',
            new_name='companion',
        ),
    ]
