# Generated by Django 4.2.3 on 2023-08-12 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Companion', '0004_rename_companion_cocomment_companion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companion',
            name='comments_count',
        ),
    ]
