# Generated by Django 4.2.3 on 2023-08-13 16:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Companion', '0005_remove_companion_comments_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='companion',
            name='scraped_user',
            field=models.ManyToManyField(blank=True, related_name='bookmark_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
