# Generated by Django 4.2.3 on 2023-08-14 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Companion", "0006_companion_scraped_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="companion",
            name="isSave",
            field=models.BooleanField(default=False),
        ),
    ]
