# Generated by Django 4.2.3 on 2023-08-14 14:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Companion", "0007_companion_issave"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companion",
            name="scraped_user",
            field=models.ManyToManyField(
                blank=True, related_name="scarped_users", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
