# Generated by Django 4.2.3 on 2023-08-12 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Record_Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='record_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('weather', models.CharField(max_length=50)),
                ('body', models.TextField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views', models.PositiveSmallIntegerField(default=0)),
                ('likes', models.PositiveSmallIntegerField(default=0)),
                ('photos', models.ManyToManyField(blank=True, related_name='Record_Photo', to='Record.record_photo')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rcomments', to='Record.record')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('where', models.CharField(max_length=80)),
                ('what', models.CharField(max_length=100)),
                ('how', models.CharField(max_length=100)),
                ('tag_field', models.CharField(default=0, max_length=80, null=True)),
                ('card_photo_1', models.ImageField(null=True, upload_to='record_photos/')),
                ('card_photo_2', models.ImageField(null=True, upload_to='record_photos/')),
                ('card_photo_3', models.ImageField(null=True, upload_to='record_photos/')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='Record.record')),
                ('tag', models.ManyToManyField(blank=True, to='Record.tag')),
            ],
        ),
    ]
