# Generated by Django 4.2.3 on 2023-08-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='views',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
