# Generated by Django 4.2.3 on 2023-08-16 13:53

import Record.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='card_photo_1',
            field=models.ImageField(null=True, upload_to=Record.models.image_upload_path),
        ),
        migrations.AlterField(
            model_name='record',
            name='card_photo_2',
            field=models.ImageField(null=True, upload_to=Record.models.image_upload_path),
        ),
        migrations.AlterField(
            model_name='record',
            name='card_photo_3',
            field=models.ImageField(null=True, upload_to=Record.models.image_upload_path),
        ),
        migrations.AlterField(
            model_name='record_photo',
            name='image',
            field=models.ImageField(upload_to=Record.models.image_upload_path),
        ),
        migrations.AlterField(
            model_name='upload_image',
            name='url',
            field=models.ImageField(upload_to=Record.models.image_upload_path),
        ),
    ]
