# Generated by Django 4.2.3 on 2023-08-18 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Record', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='photos',
        ),
    ]
