# Generated by Django 4.2.3 on 2023-08-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='body',
            field=models.TextField(max_length=2000),
        ),
    ]
