# Generated by Django 4.2.3 on 2023-08-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Record', '0002_record_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='likes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
