# Generated by Django 4.2.3 on 2023-08-18 10:27

import Record.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Record', '0002_remove_record_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='card_photo_2',
            field=models.ImageField(blank=True, null=True, upload_to=Record.models.image_upload_path),
        ),
        migrations.AlterField(
            model_name='record',
            name='card_photo_3',
            field=models.ImageField(blank=True, null=True, upload_to=Record.models.image_upload_path),
        ),
    ]
