# Generated by Django 4.2.3 on 2023-08-13 10:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Record', '0003_record_scrap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='scrap',
        ),
        migrations.AddField(
            model_name='card',
            name='card_scrap',
            field=models.ManyToManyField(blank=True, related_name='card_scraps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='record',
            name='record_scrap',
            field=models.ManyToManyField(blank=True, related_name='record_scraps', to=settings.AUTH_USER_MODEL),
        ),
    ]
