# Generated by Django 4.2.3 on 2023-08-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Record', '0003_record_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record_Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='record_photos/')),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='photos',
            field=models.ManyToManyField(related_name='Record_Photo', to='Record.record_photo'),
        ),
    ]
