# Generated by Django 4.2.3 on 2023-08-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Record', '0004_record_photo_record_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='photos',
            field=models.ManyToManyField(blank=True, null=True, related_name='Record_Photo', to='Record.record_photo'),
        ),
    ]
