# Generated by Django 4.2.3 on 2023-08-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Record', '0005_upload_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_image',
            name='url',
            field=models.ImageField(upload_to='record_photos/'),
        ),
    ]
