# Generated by Django 4.2.3 on 2023-08-15 07:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Record', '0006_alter_upload_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='likes',
        ),
        migrations.AddField(
            model_name='record',
            name='rlike',
            field=models.ManyToManyField(blank=True, related_name='Rlikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='record',
            name='rlike_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
