# Generated by Django 4.2.3 on 2023-08-12 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Record', '0006_alter_record_photos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('where', models.CharField(max_length=80)),
                ('what', models.CharField(max_length=100)),
                ('how', models.CharField(max_length=100)),
                ('card_photo_1', models.ImageField(upload_to='record_photos/')),
                ('card_photo_2', models.ImageField(upload_to='record_photos/')),
                ('card_photo_3', models.ImageField(upload_to='record_photos/')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Record.record')),
            ],
        ),
    ]
