# Generated by Django 4.2.3 on 2023-08-15 07:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Record', '0007_remove_record_likes_record_rlike_record_rlike_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='rlike',
            field=models.ManyToManyField(blank=True, related_name='rlikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
