# Generated by Django 4.2.3 on 2023-08-12 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Record', '0007_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rcomment',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rcomments', to='Record.record'),
        ),
    ]
