# Generated by Django 4.2.3 on 2023-08-12 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Record', '0008_alter_rcomment_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='Record.record'),
        ),
    ]
