# Generated by Django 4.2.3 on 2023-08-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Record', '0009_alter_card_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_photo_1',
            field=models.ImageField(null=True, upload_to='record_photos/'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_photo_2',
            field=models.ImageField(null=True, upload_to='record_photos/'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_photo_3',
            field=models.ImageField(null=True, upload_to='record_photos/'),
        ),
    ]
